export type {
  BaseMapping,
  Constraint,
  ConfigurationMetadata,
  DataType,
  DraftBundle,
  DraftConfiguration,
  ExportConfiguration,
  ExportInputMapping,
  ExportOutputMapping,
  ImportBaseline,
  InputMapping,
  Mapping,
  MappingType,
  OutputMapping,
  ValidationError,
  VersionTag,
} from "@shared/configuration";
